

file1.txt:
	touch file1.txt
#target file:dependency file
	#list of commands which helps to complete target file
	
	
	
#target file - is a file which have to be build
#dependency file - is a file in which target file is dependent[on every file change we can run the command "make target_file" by this the target file will get update
#list of commands - commands which help to build the target
#


file2.txt:dependency.txt
	echo "This is file2" > file2.txt
	grep -P "v[0-9].*[0-9]" dependency.txt >> file2.txt
	
